apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      name: database
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: savitxr/2-tier-db:1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
#            - name: DATA_SOURCE_URL
 #             value: "jdbc:mysql://db-svc:3306/jb_db"
  #          - name: DATA_SOURCE_USERNAME
   #           value: "appuser"
    #        - name: DATA_SOURCE_PASSWORD
     #         value: "password123"
      #      - name: SPRING_JPA_HIBERNATE_DDL_AUTO
       #       value: "update"
