spring.application.name=${APP_NAME:app}

# MySQL Database Configuration
spring.datasource.url=${DATA_SOURCE_URL:jdbc:mysql://localhost:3306/jb_db}
spring.datasource.username=${DATA_SOURCE_USERNAME:appuser}
spring.datasource.password=${DATA_SOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=$(SPRING_JPA_HIBERNATE_DDL_AUTO:update)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080
