apiVersion: v1
kind: Service
metadata:
  name: nodejssd
  labels:
    app: nodejssd
spec:
  type: NodePort
  selector:
    app: nodejsfront
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
