apiVersion: v1
kind: Pod
metadata:
  name: pv-demo-pod
  labels:
    app: pv-demo-pod
spec:
  containers:
    - name: nginx-pv
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: local
          mountPath: /usr/share/nginx/html
  volumes:
    - name: local
      persistentVolumeClaim:
        claimName: task2-pvc1
