apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ngin
  name: ngin
spec:
  containers:
  - name: ngin
    image: nginx
    command: ["sleep","3600"]
    ports:
    - containerPort: 80
    volumeMounts:
      - name: nfs
        mountPath: /mnt/path
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfspvc
