apiVersion: v1
kind: Pod
metadata:
  name: apppod
  labels:
    app: apppod
spec:
  containers:
  - name: nginx-cont
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /cache
      name: host-space
  - name: busy-cont1
    image: busybox
    command: ["sh","-c","while true; do echo 'Hello noob'; sleep 600; done"]
    volumeMounts:
    - mountPath: /afridimygoat
      name: host-space
  volumes:
  - name: host-space
    hostPath:
      path: /data/app
      type: DirectoryOrCreate
